### ISSUE TITLE
Make sure the same nixpkgs tree is used for all developers

### ISSUE THREAD

**Issue by eskimor** [gonimo/gonimo-server#3]

**Comment by eskimor** [comment]
I'll take care of this, @m3phisto if you have any inputs regarding this or some insights I don't have - let me know.

**Comment by m3phisto** [comment]
Might that have anything to do with the recent "nix-channel --update" and subsequent "nixops deploy" I did when deploying the nagios setup? Did that mess things up for you? I'm sorry if it did. What happened exactly?
I need a bit more information to venture a guess on how to fix these issues. Also, I need to sort out which nixpkgs tree my nixops installation actually uses. ;)

**Comment by eskimor** [comment]
No, no - no problems there. It just bothers me that the nixpkgs tree to be used is determined by the developers system default. It should be specified in gonimo-server itself so everyone gets guaranteed the same results - this is what nixops is all about after all. If you are clueless, then I have more clue than you - so I will take care of that ;-)

**Comment by m3phisto** [comment]
Gotcha. I was under the impression that my actions broke something for you. Thanks for clarifying. Thanks for taking care of that. I can see why it's annoying.
